import type { Transaction } from "@/lib/utils/db";
import { db } from "@/lib/utils/db";

type TransactionInput = Omit<Transaction, "id">;

const transactions: TransactionInput[] = [
  // ==================== NOVEMBER 2025 ====================
  {
    type: "topup",
    itemName: "Salary Nov 2025",
    amount: 8200000,
    category: "topup",
    transactionDate: new Date(2025, 10, 1),
    balanceAfter: 8200000,
    aiScore: null,
    aiVerdict: null,
    aiReason: null,
    fullAnalysis: null,
    createdAt: new Date(2025, 10, 1),
  },
  {
    type: "purchase",
    itemName: "Starlink - Internet bulanan",
    amount: 750000,
    category: "bills",
    transactionDate: new Date(2025, 10, 3),
    balanceAfter: 7450000,
    aiScore: 80,
    aiVerdict: "Worth It Score: 80/100 - Necessary expense",
    aiReason: "Internet for work",
    fullAnalysis: "Stable connection needed",
    createdAt: new Date(2025, 10, 3),
  },
  {
    type: "purchase",
    itemName: "Pertamina - Fuel",
    amount: 300000,
    category: "transport",
    transactionDate: new Date(2025, 10, 5),
    balanceAfter: 7150000,
    aiScore: 85,
    aiVerdict: "Worth It Score: 85/100 - Essential",
    aiReason: "Daily commute",
    fullAnalysis: "Reasonable fuel cost",
    createdAt: new Date(2025, 10, 5),
  },
  {
    type: "purchase",
    itemName: "Superindo - Belanja mingguan",
    amount: 420000,
    category: "groceries",
    transactionDate: new Date(2025, 10, 8),
    balanceAfter: 6730000,
    aiScore: 88,
    aiVerdict: "Worth It Score: 88/100 - Smart",
    aiReason: "Weekly groceries",
    fullAnalysis: "Fresh and essential",
    createdAt: new Date(2025, 10, 8),
  },
  {
    type: "purchase",
    itemName: "Sushi Hiro - Dinner",
    amount: 185000,
    category: "dining",
    transactionDate: new Date(2025, 10, 12),
    balanceAfter: 6545000,
    aiScore: 70,
    aiVerdict: "Worth It Score: 70/100 - Occasional treat",
    aiReason: "Weekend celebration",
    fullAnalysis: "Okay if not frequent",
    createdAt: new Date(2025, 10, 12),
  },
  {
    type: "purchase",
    itemName: "Uniqlo - Hoodie",
    amount: 399000,
    category: "clothing",
    transactionDate: new Date(2025, 10, 15),
    balanceAfter: 6146000,
    aiScore: 60,
    aiVerdict: "Worth It Score: 60/100 - Consider budget",
    aiReason: "Optional clothing",
    fullAnalysis: "Could wait for sale",
    createdAt: new Date(2025, 10, 15),
  },
  {
    type: "purchase",
    itemName: "Netflix subscription",
    amount: 54000,
    category: "entertainment",
    transactionDate: new Date(2025, 10, 18),
    balanceAfter: 6092000,
    aiScore: 80,
    aiVerdict: "Worth It Score: 80/100 - Good value",
    aiReason: "Daily entertainment",
    fullAnalysis: "Cheap per hour",
    createdAt: new Date(2025, 10, 18),
  },
  {
    type: "purchase",
    itemName: "JNE - Ongkir kirim paket",
    amount: 45000,
    category: "shipping",
    transactionDate: new Date(2025, 10, 20),
    balanceAfter: 6047000,
    aiScore: 90,
    aiVerdict: "Worth It Score: 90/100 - Efficient",
    aiReason: "Business need",
    fullAnalysis: "Cheap and fast",
    createdAt: new Date(2025, 10, 20),
  },
  {
    type: "purchase",
    itemName: "Donation - Local orphanage",
    amount: 100000,
    category: "charity",
    transactionDate: new Date(2025, 10, 23),
    balanceAfter: 5947000,
    aiScore: 100,
    aiVerdict: "Worth It Score: 100/100 - Noble",
    aiReason: "Social responsibility",
    fullAnalysis: "Always worth it",
    createdAt: new Date(2025, 10, 23),
  },
  {
    type: "purchase",
    itemName: "Skincare - Facial wash",
    amount: 125000,
    category: "personal care",
    transactionDate: new Date(2025, 10, 27),
    balanceAfter: 5822000,
    aiScore: 80,
    aiVerdict: "Worth It Score: 80/100 - Basic need",
    aiReason: "Daily use",
    fullAnalysis: "Reasonable price",
    createdAt: new Date(2025, 10, 27),
  },

  // ==================== DECEMBER 2025 ====================
  {
    type: "topup",
    itemName: "Salary Dec 2025 + Bonus",
    amount: 9500000,
    category: "topup",
    transactionDate: new Date(2025, 11, 1),
    balanceAfter: 9500000,
    aiScore: null,
    aiVerdict: null,
    aiReason: null,
    fullAnalysis: null,
    createdAt: new Date(2025, 11, 1),
  },
  {
    type: "purchase",
    itemName: "Telkom - Internet & TV",
    amount: 550000,
    category: "bills",
    transactionDate: new Date(2025, 11, 2),
    balanceAfter: 8950000,
    aiScore: 85,
    aiVerdict: "Worth It Score: 85/100 - Essential",
    aiReason: "Work from home",
    fullAnalysis: "Reliable ISP",
    createdAt: new Date(2025, 11, 2),
  },
  {
    type: "purchase",
    itemName: "Gojek - Transport 5x",
    amount: 125000,
    category: "transport",
    transactionDate: new Date(2025, 11, 5),
    balanceAfter: 8825000,
    aiScore: 70,
    aiVerdict: "Worth It Score: 70/100 - Convenience",
    aiReason: "No vehicle",
    fullAnalysis: "Acceptable",
    createdAt: new Date(2025, 11, 5),
  },
  {
    type: "purchase",
    itemName: "Christmas Gift - Mom",
    amount: 500000,
    category: "gift",
    transactionDate: new Date(2025, 11, 8),
    balanceAfter: 8325000,
    aiScore: 95,
    aiVerdict: "Worth It Score: 95/100 - Heartwarming",
    aiReason: "Family gift",
    fullAnalysis: "Great value for happiness",
    createdAt: new Date(2025, 11, 8),
  },
  {
    type: "purchase",
    itemName: "Superindo - Belanja akhir tahun",
    amount: 600000,
    category: "groceries",
    transactionDate: new Date(2025, 11, 12),
    balanceAfter: 7725000,
    aiScore: 80,
    aiVerdict: "Worth It Score: 80/100 - Bulk buy",
    aiReason: "Stock for holidays",
    fullAnalysis: "Smart to avoid crowds",
    createdAt: new Date(2025, 11, 12),
  },
  {
    type: "purchase",
    itemName: "Starbucks - Coffee",
    amount: 55000,
    category: "dining",
    transactionDate: new Date(2025, 11, 15),
    balanceAfter: 7670000,
    aiScore: 50,
    aiVerdict: "Worth It Score: 50/100 - Luxury",
    aiReason: "Expensive coffee",
    fullAnalysis: "Better brew at home",
    createdAt: new Date(2025, 11, 15),
  },
  {
    type: "purchase",
    itemName: "Tokopedia - Powerbank",
    amount: 250000,
    category: "electronics",
    transactionDate: new Date(2025, 11, 17),
    balanceAfter: 7420000,
    aiScore: 85,
    aiVerdict: "Worth It Score: 85/100 - Useful",
    aiReason: "Phone always dies",
    fullAnalysis: "Good investment",
    createdAt: new Date(2025, 11, 17),
  },
  {
    type: "purchase",
    itemName: "CGV - Cinema 2 tickets",
    amount: 90000,
    category: "entertainment",
    transactionDate: new Date(2025, 11, 20),
    balanceAfter: 7330000,
    aiScore: 75,
    aiVerdict: "Worth It Score: 75/100 - Fine",
    aiReason: "Movie night",
    fullAnalysis: "Standard price",
    createdAt: new Date(2025, 11, 20),
  },
  {
    type: "purchase",
    itemName: "Nasi Padang - Lunch (6x)",
    amount: 180000,
    category: "dining",
    transactionDate: new Date(2025, 11, 23),
    balanceAfter: 7150000,
    aiScore: 75,
    aiVerdict: "Worth It Score: 75/100 - Fair",
    aiReason: "Cheap eats",
    fullAnalysis: "Better than fast food",
    createdAt: new Date(2025, 11, 23),
  },
  {
    type: "purchase",
    itemName: "Pajak kendaraan",
    amount: 1500000,
    category: "tax",
    transactionDate: new Date(2025, 11, 27),
    balanceAfter: 5650000,
    aiScore: 90,
    aiVerdict: "Worth It Score: 90/100 - Mandatory",
    aiReason: "Must pay",
    fullAnalysis: "No choice",
    createdAt: new Date(2025, 11, 27),
  },
  {
    type: "purchase",
    itemName: "Infak masjid",
    amount: 50000,
    category: "charity",
    transactionDate: new Date(2025, 11, 29),
    balanceAfter: 5600000,
    aiScore: 100,
    aiVerdict: "Worth It Score: 100/100 - Blessing",
    aiReason: "Religious duty",
    fullAnalysis: "Multiply reward",
    createdAt: new Date(2025, 11, 29),
  },

  // ==================== JANUARY 2026 ====================
  {
    type: "topup",
    itemName: "Salary Jan 2026",
    amount: 8500000,
    category: "topup",
    transactionDate: new Date(2026, 0, 2),
    balanceAfter: 8500000,
    aiScore: null,
    aiVerdict: null,
    aiReason: null,
    fullAnalysis: null,
    createdAt: new Date(2026, 0, 2),
  },
  {
    type: "purchase",
    itemName: "Routine checkup - Doctor",
    amount: 350000,
    category: "health",
    transactionDate: new Date(2026, 0, 4),
    balanceAfter: 8150000,
    aiScore: 95,
    aiVerdict: "Worth It Score: 95/100 - Essential",
    aiReason: "Health first",
    fullAnalysis: "Prevention is key",
    createdAt: new Date(2026, 0, 4),
  },
  {
    type: "purchase",
    itemName: "Gym membership monthly",
    amount: 450000,
    category: "fitness",
    transactionDate: new Date(2026, 0, 5),
    balanceAfter: 7700000,
    aiScore: 88,
    aiVerdict: "Worth It Score: 88/100 - Healthy habit",
    aiReason: "Consistent workout",
    fullAnalysis: "Good for long term",
    createdAt: new Date(2026, 0, 5),
  },
  {
    type: "purchase",
    itemName: "PLN - Token listrik",
    amount: 350000,
    category: "bills",
    transactionDate: new Date(2026, 0, 7),
    balanceAfter: 7350000,
    aiScore: 90,
    aiVerdict: "Worth It Score: 90/100 - Basic",
    aiReason: "Electricity",
    fullAnalysis: "No electricity no life",
    createdAt: new Date(2026, 0, 7),
  },
  {
    type: "purchase",
    itemName: "Alfamart - Snacks & drinks",
    amount: 85000,
    category: "groceries",
    transactionDate: new Date(2026, 0, 10),
    balanceAfter: 7265000,
    aiScore: 65,
    aiVerdict: "Worth It Score: 65/100 - Meh",
    aiReason: "Impulse buy",
    fullAnalysis: "Could skip",
    createdAt: new Date(2026, 0, 10),
  },
  {
    type: "purchase",
    itemName: "Laundry service",
    amount: 120000,
    category: "services",
    transactionDate: new Date(2026, 0, 14),
    balanceAfter: 7145000,
    aiScore: 85,
    aiVerdict: "Worth It Score: 85/100 - Time saver",
    aiReason: "Saves 3 hours",
    fullAnalysis: "Worth it for busy week",
    createdAt: new Date(2026, 0, 14),
  },
  {
    type: "purchase",
    itemName: "Jasa bersih-bersih rumah",
    amount: 200000,
    category: "services",
    transactionDate: new Date(2026, 0, 18),
    balanceAfter: 6945000,
    aiScore: 70,
    aiVerdict: "Worth It Score: 70/100 - Luxury",
    aiReason: "Convenience",
    fullAnalysis: "Could DIY but okay",
    createdAt: new Date(2026, 0, 18),
  },
  {
    type: "purchase",
    itemName: "Bensin motor (full tank)",
    amount: 50000,
    category: "transport",
    transactionDate: new Date(2026, 0, 21),
    balanceAfter: 6895000,
    aiScore: 85,
    aiVerdict: "Worth It Score: 85/100 - Standard",
    aiReason: "Daily ride",
    fullAnalysis: "Normal expense",
    createdAt: new Date(2026, 0, 21),
  },
  {
    type: "purchase",
    itemName: "Donation - Local orphanage",
    amount: 100000,
    category: "charity",
    transactionDate: new Date(2026, 0, 25),
    balanceAfter: 6795000,
    aiScore: 100,
    aiVerdict: "Worth It Score: 100/100 - Noble",
    aiReason: "Social responsibility",
    fullAnalysis: "Always worth it",
    createdAt: new Date(2026, 0, 25),
  },
  {
    type: "purchase",
    itemName: "Buku - Atomic Habits",
    amount: 95000,
    category: "education",
    transactionDate: new Date(2026, 0, 28),
    balanceAfter: 6700000,
    aiScore: 98,
    aiVerdict: "Worth It Score: 98/100 - Best investment",
    aiReason: "Self improvement",
    fullAnalysis: "Cheap for lifetime skill",
    createdAt: new Date(2026, 0, 28),
  },

  // ==================== FEBRUARY 2026 ====================
  {
    type: "topup",
    itemName: "Salary Feb 2026",
    amount: 8500000,
    category: "topup",
    transactionDate: new Date(2026, 1, 1),
    balanceAfter: 8500000,
    aiScore: null,
    aiVerdict: null,
    aiReason: null,
    fullAnalysis: null,
    createdAt: new Date(2026, 1, 1),
  },
  {
    type: "purchase",
    itemName: "Telkom - Internet & TV",
    amount: 550000,
    category: "bills",
    transactionDate: new Date(2026, 1, 3),
    balanceAfter: 7950000,
    aiScore: 85,
    aiVerdict: "Worth It Score: 85/100 - Essential",
    aiReason: "Work from home",
    fullAnalysis: "Reliable ISP",
    createdAt: new Date(2026, 1, 3),
  },
  {
    type: "purchase",
    itemName: "Gym membership monthly",
    amount: 450000,
    category: "fitness",
    transactionDate: new Date(2026, 1, 5),
    balanceAfter: 7500000,
    aiScore: 88,
    aiVerdict: "Worth It Score: 88/100 - Healthy habit",
    aiReason: "Consistent workout",
    fullAnalysis: "Good for long term",
    createdAt: new Date(2026, 1, 5),
  },
  {
    type: "purchase",
    itemName: "Valentine gift - Flower & chocolate",
    amount: 350000,
    category: "gift",
    transactionDate: new Date(2026, 1, 14),
    balanceAfter: 7150000,
    aiScore: 90,
    aiVerdict: "Worth It Score: 90/100 - Love",
    aiReason: "Make partner happy",
    fullAnalysis: "Priceless memory",
    createdAt: new Date(2026, 1, 14),
  },
  {
    type: "purchase",
    itemName: "Pizza Hut - Delivery",
    amount: 145000,
    category: "dining",
    transactionDate: new Date(2026, 1, 15),
    balanceAfter: 7005000,
    aiScore: 60,
    aiVerdict: "Worth It Score: 60/100 - Junk",
    aiReason: "Unhealthy",
    fullAnalysis: "Occasional only",
    createdAt: new Date(2026, 1, 15),
  },
  {
    type: "purchase",
    itemName: "Bimbel online - English",
    amount: 400000,
    category: "education",
    transactionDate: new Date(2026, 1, 18),
    balanceAfter: 6605000,
    aiScore: 95,
    aiVerdict: "Worth It Score: 95/100 - Investment",
    aiReason: "Skill upgrade",
    fullAnalysis: "High ROI",
    createdAt: new Date(2026, 1, 18),
  },
  {
    type: "purchase",
    itemName: "Dentist - Scaling",
    amount: 500000,
    category: "health",
    transactionDate: new Date(2026, 1, 20),
    balanceAfter: 6105000,
    aiScore: 92,
    aiVerdict: "Worth It Score: 92/100 - Preventive",
    aiReason: "Dental hygiene",
    fullAnalysis: "Avoid bigger cost later",
    createdAt: new Date(2026, 1, 20),
  },
  {
    type: "purchase",
    itemName: "Potong rambut - Barbershop",
    amount: 60000,
    category: "personal care",
    transactionDate: new Date(2026, 1, 22),
    balanceAfter: 6045000,
    aiScore: 85,
    aiVerdict: "Worth It Score: 85/100 - Neat",
    aiReason: "Look professional",
    fullAnalysis: "Fair price",
    createdAt: new Date(2026, 1, 22),
  },
  {
    type: "purchase",
    itemName: "Vitamin & supplement",
    amount: 180000,
    category: "health",
    transactionDate: new Date(2026, 1, 25),
    balanceAfter: 5865000,
    aiScore: 88,
    aiVerdict: "Worth It Score: 88/100 - Health",
    aiReason: "Boost immunity",
    fullAnalysis: "Good habit",
    createdAt: new Date(2026, 1, 25),
  },
  {
    type: "purchase",
    itemName: "Pertalite - Fuel",
    amount: 320000,
    category: "transport",
    transactionDate: new Date(2026, 1, 27),
    balanceAfter: 5545000,
    aiScore: 80,
    aiVerdict: "Worth It Score: 80/100 - Essential",
    aiReason: "Commute",
    fullAnalysis: "Average cost",
    createdAt: new Date(2026, 1, 27),
  },

  // ==================== MARCH 2026 ====================
  {
    type: "topup",
    itemName: "Salary Mar 2026",
    amount: 9000000,
    category: "topup",
    transactionDate: new Date(2026, 2, 1),
    balanceAfter: 9000000,
    aiScore: null,
    aiVerdict: null,
    aiReason: null,
    fullAnalysis: null,
    createdAt: new Date(2026, 2, 1),
  },
  {
    type: "purchase",
    itemName: "PLN - Token listrik",
    amount: 350000,
    category: "bills",
    transactionDate: new Date(2026, 2, 3),
    balanceAfter: 8650000,
    aiScore: 90,
    aiVerdict: "Worth It Score: 90/100 - Basic",
    aiReason: "Electricity",
    fullAnalysis: "No electricity no life",
    createdAt: new Date(2026, 2, 3),
  },
  {
    type: "purchase",
    itemName: "IKEA - Lampu meja",
    amount: 299000,
    category: "home",
    transactionDate: new Date(2026, 2, 5),
    balanceAfter: 8351000,
    aiScore: 80,
    aiVerdict: "Worth It Score: 80/100 - Functional",
    aiReason: "Better lighting",
    fullAnalysis: "Good design",
    createdAt: new Date(2026, 2, 5),
  },
  {
    type: "purchase",
    itemName: "Tiket pesawat - Lebaran homecoming",
    amount: 1200000,
    category: "travel",
    transactionDate: new Date(2026, 2, 8),
    balanceAfter: 7151000,
    aiScore: 85,
    aiVerdict: "Worth It Score: 85/100 - Family",
    aiReason: "Meet parents",
    fullAnalysis: "Book early",
    createdAt: new Date(2026, 2, 8),
  },
  {
    type: "purchase",
    itemName: "Gym membership monthly",
    amount: 450000,
    category: "fitness",
    transactionDate: new Date(2026, 2, 10),
    balanceAfter: 6701000,
    aiScore: 88,
    aiVerdict: "Worth It Score: 88/100 - Healthy habit",
    aiReason: "Consistent workout",
    fullAnalysis: "Good for long term",
    createdAt: new Date(2026, 2, 10),
  },
  {
    type: "purchase",
    itemName: "Batch - All You Can Eat BBQ",
    amount: 250000,
    category: "dining",
    transactionDate: new Date(2026, 2, 14),
    balanceAfter: 6451000,
    aiScore: 70,
    aiVerdict: "Worth It Score: 70/100 - Splurge",
    aiReason: "Celebration",
    fullAnalysis: "Good but pricey",
    createdAt: new Date(2026, 2, 14),
  },
  {
    type: "purchase",
    itemName: "Air mineral galon",
    amount: 20000,
    category: "groceries",
    transactionDate: new Date(2026, 2, 17),
    balanceAfter: 6431000,
    aiScore: 95,
    aiVerdict: "Worth It Score: 95/100 - Essential",
    aiReason: "Hydration",
    fullAnalysis: "Cheap necessity",
    createdAt: new Date(2026, 2, 17),
  },
  {
    type: "purchase",
    itemName: "Belanja bulanan - Pasar tradisional",
    amount: 700000,
    category: "groceries",
    transactionDate: new Date(2026, 2, 20),
    balanceAfter: 5731000,
    aiScore: 88,
    aiVerdict: "Worth It Score: 88/100 - Smart",
    aiReason: "Cheaper than supermarket",
    fullAnalysis: "Fresh ingredients",
    createdAt: new Date(2026, 2, 20),
  },
  {
    type: "purchase",
    itemName: "Bensin motor (full tank)",
    amount: 50000,
    category: "transport",
    transactionDate: new Date(2026, 2, 23),
    balanceAfter: 5681000,
    aiScore: 85,
    aiVerdict: "Worth It Score: 85/100 - Standard",
    aiReason: "Daily ride",
    fullAnalysis: "Normal expense",
    createdAt: new Date(2026, 2, 23),
  },
  {
    type: "purchase",
    itemName: "Parkir langganan kantor",
    amount: 220000,
    category: "transport",
    transactionDate: new Date(2026, 2, 25),
    balanceAfter: 5461000,
    aiScore: 75,
    aiVerdict: "Worth It Score: 75/100 - Necessary",
    aiReason: "Monthly pass",
    fullAnalysis: "Cheaper than daily",
    createdAt: new Date(2026, 2, 25),
  },
  {
    type: "purchase",
    itemName: "Infak masjid",
    amount: 50000,
    category: "charity",
    transactionDate: new Date(2026, 2, 28),
    balanceAfter: 5411000,
    aiScore: 100,
    aiVerdict: "Worth It Score: 100/100 - Blessing",
    aiReason: "Religious duty",
    fullAnalysis: "Multiply reward",
    createdAt: new Date(2026, 2, 28),
  },

  // ==================== APRIL 2026 ====================
  {
    type: "topup",
    itemName: "Salary Apr 2026",
    amount: 8500000,
    category: "topup",
    transactionDate: new Date(2026, 3, 1),
    balanceAfter: 8500000,
    aiScore: null,
    aiVerdict: null,
    aiReason: null,
    fullAnalysis: null,
    createdAt: new Date(2026, 3, 1),
  },
  {
    type: "purchase",
    itemName: "BPJS Kesehatan",
    amount: 150000,
    category: "insurance",
    transactionDate: new Date(2026, 3, 2),
    balanceAfter: 8350000,
    aiScore: 95,
    aiVerdict: "Worth It Score: 95/100 - Protection",
    aiReason: "Mandatory & useful",
    fullAnalysis: "Peace of mind",
    createdAt: new Date(2026, 3, 2),
  },
  {
    type: "purchase",
    itemName: "Langganan VPN",
    amount: 120000,
    category: "subscription",
    transactionDate: new Date(2026, 3, 4),
    balanceAfter: 8230000,
    aiScore: 80,
    aiVerdict: "Worth It Score: 80/100 - Privacy",
    aiReason: "Secure browsing",
    fullAnalysis: "Good for security",
    createdAt: new Date(2026, 3, 4),
  },
  {
    type: "purchase",
    itemName: "Belanja kucing - Pasir & makanan",
    amount: 180000,
    category: "pet",
    transactionDate: new Date(2026, 3, 7),
    balanceAfter: 8050000,
    aiScore: 92,
    aiVerdict: "Worth It Score: 92/100 - Pet care",
    aiReason: "Furry friend",
    fullAnalysis: "Responsibility",
    createdAt: new Date(2026, 3, 7),
  },
  {
    type: "purchase",
    itemName: "Buku - Atomic Habits",
    amount: 95000,
    category: "education",
    transactionDate: new Date(2026, 3, 10),
    balanceAfter: 7955000,
    aiScore: 98,
    aiVerdict: "Worth It Score: 98/100 - Best investment",
    aiReason: "Self improvement",
    fullAnalysis: "Cheap for lifetime skill",
    createdAt: new Date(2026, 3, 10),
  },
  {
    type: "purchase",
    itemName: "Minum - Es kopi kekinian (10x)",
    amount: 250000,
    category: "dining",
    transactionDate: new Date(2026, 3, 13),
    balanceAfter: 7705000,
    aiScore: 45,
    aiVerdict: "Worth It Score: 45/100 - Waste",
    aiReason: "Too frequent",
    fullAnalysis: "Reduce to save",
    createdAt: new Date(2026, 3, 13),
  },
  {
    type: "purchase",
    itemName: "Kado ultah teman",
    amount: 200000,
    category: "gift",
    transactionDate: new Date(2026, 3, 16),
    balanceAfter: 7505000,
    aiScore: 85,
    aiVerdict: "Worth It Score: 85/100 - Social",
    aiReason: "Strengthen friendship",
    fullAnalysis: "Reasonable",
    createdAt: new Date(2026, 3, 16),
  },
  {
    type: "purchase",
    itemName: "Tinta printer",
    amount: 180000,
    category: "office",
    transactionDate: new Date(2026, 3, 19),
    balanceAfter: 7325000,
    aiScore: 88,
    aiVerdict: "Worth It Score: 88/100 - Needed",
    aiReason: "Print documents",
    fullAnalysis: "Essential for work",
    createdAt: new Date(2026, 3, 19),
  },
  {
    type: "purchase",
    itemName: "Repair HP - Ganti LCD",
    amount: 850000,
    category: "repair",
    transactionDate: new Date(2026, 3, 22),
    balanceAfter: 6475000,
    aiScore: 90,
    aiVerdict: "Worth It Score: 90/100 - Save device",
    aiReason: "Cheaper than new phone",
    fullAnalysis: "Wise decision",
    createdAt: new Date(2026, 3, 22),
  },
  {
    type: "purchase",
    itemName: "Nonton konser online",
    amount: 150000,
    category: "entertainment",
    transactionDate: new Date(2026, 3, 25),
    balanceAfter: 6325000,
    aiScore: 70,
    aiVerdict: "Worth It Score: 70/100 - Fun",
    aiReason: "Enjoy hobby",
    fullAnalysis: "Better than live (cheaper)",
    createdAt: new Date(2026, 3, 25),
  },
  {
    type: "purchase",
    itemName: "Infak masjid",
    amount: 50000,
    category: "charity",
    transactionDate: new Date(2026, 3, 28),
    balanceAfter: 6275000,
    aiScore: 100,
    aiVerdict: "Worth It Score: 100/100 - Blessing",
    aiReason: "Religious duty",
    fullAnalysis: "Multiply reward",
    createdAt: new Date(2026, 3, 28),
  },

  // ==================== MAY 2026 (max May 1 only) ====================
  {
    type: "topup",
    itemName: "Salary May 2026",
    amount: 8500000,
    category: "topup",
    transactionDate: new Date(2026, 4, 1),
    balanceAfter: 8500000,
    aiScore: null,
    aiVerdict: null,
    aiReason: null,
    fullAnalysis: null,
    createdAt: new Date(2026, 4, 1),
  },
  {
    type: "purchase",
    itemName: "Indomaret - Groceries",
    amount: 250000,
    category: "groceries",
    transactionDate: new Date(2026, 4, 1, 9, 0, 0),
    balanceAfter: 8250000,
    aiScore: 85,
    aiVerdict: "Worth It Score: 85/100 - Good planning",
    aiReason: "Essential groceries",
    fullAnalysis: "Smart to stock up early",
    createdAt: new Date(2026, 4, 1, 9, 0, 0),
  },
  {
    type: "purchase",
    itemName: "Pulsa & paket data",
    amount: 100000,
    category: "bills",
    transactionDate: new Date(2026, 4, 1, 11, 0, 0),
    balanceAfter: 8150000,
    aiScore: 90,
    aiVerdict: "Worth It Score: 90/100 - Connect",
    aiReason: "Internet access",
    fullAnalysis: "Essential",
    createdAt: new Date(2026, 4, 1, 11, 0, 0),
  },
  {
    type: "purchase",
    itemName: "Makan siang - Warteg (15x)",
    amount: 375000,
    category: "dining",
    transactionDate: new Date(2026, 4, 1, 13, 0, 0),
    balanceAfter: 7775000,
    aiScore: 85,
    aiVerdict: "Worth It Score: 85/100 - Frugal",
    aiReason: "Cheapest meal",
    fullAnalysis: "Smart choice",
    createdAt: new Date(2026, 4, 1, 13, 0, 0),
  },
];

export async function seedTransactions() {
  try {
    // Clear existing transactions
    await db.transactions.clear();

    // Insert all transactions
    await db.transactions.bulkAdd(transactions);

    console.log(`✅ Successfully seeded ${transactions.length} transactions`);
    return { success: true, count: transactions.length };
  } catch (error) {
    console.error("Failed to seed transactions:", error);
    return { success: false, error };
  }
}

export async function clearTransactions() {
  try {
    await db.transactions.clear();

    console.log("🗑️ All transactions removed");
    return { success: true };
  } catch (error) {
    console.error("Failed to clear transactions:", error);
    return { success: false, error };
  }
}
